# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\pyqt5\leizitingshu\icon\ting.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from icon import leizi_rc
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 550)
        MainWindow.setWindowTitle('雷子的小程序')
        MainWindow.setMaximumSize(QtCore.QSize(714, 550))
        MainWindow.setStyleSheet("background-color: rgb(255, 249, 156);\n"
"font: 75 14pt \"Aharoni\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 15, 121, 21))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 40, 121, 91))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.radioButton_2.setObjectName("radioButton_2")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 541, 401))
        self.textEdit.setStyleSheet("font: 75 16pt \"Aharoni\";\n"
"background-color: rgb(162, 255, 237);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 420, 91, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/hh/play48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 490, 261, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 500, 131, 21))
        self.label_3.setStyleSheet("font: 75 9pt \"Aharoni\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 410, 181, 31))
        self.label_4.setStyleSheet("font: 75 16pt \"Aharoni\";\n"
"font: 75 10pt \"Aharoni\";")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 27))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.actionDakai = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/hh/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDakai.setIcon(icon1)
        self.actionDakai.setObjectName("actionDakai")
        self.actionTuichu = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hh/f08b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTuichu.setIcon(icon2)
        self.actionTuichu.setObjectName("actionTuichu")
        self.actionQingkong = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/hh/1173189.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQingkong.setIcon(icon3)
        self.actionQingkong.setObjectName("actionQingkong")
        self.actionJianqie = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/hh/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJianqie.setIcon(icon4)
        self.actionJianqie.setObjectName("actionJianqie")
        self.actionFuzhi = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/hh/copy_clipboard_lined.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFuzhi.setIcon(icon5)
        self.actionFuzhi.setObjectName("actionFuzhi")
        self.actionZhantie = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/hh/order.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZhantie.setIcon(icon6)
        self.actionZhantie.setObjectName("actionZhantie")
        self.action = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/hh/male-user-accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon7)
        self.action.setObjectName("action")
        self.actionZuozhe = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/hh/about-me.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZuozhe.setIcon(icon8)
        self.actionZuozhe.setObjectName("actionZuozhe")
        self.actionRuanjian = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/hh/1170244.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRuanjian.setIcon(icon9)
        self.actionRuanjian.setObjectName("actionRuanjian")
        self.menu.addAction(self.actionDakai)
        self.menu.addAction(self.actionTuichu)
        self.menu.addAction(self.actionQingkong)
        self.menu_2.addAction(self.actionJianqie)
        self.menu_2.addAction(self.actionFuzhi)
        self.menu_2.addAction(self.actionZhantie)
        self.menu_3.addAction(self.action)
        self.menu_3.addAction(self.actionZuozhe)
        self.menu_3.addAction(self.actionRuanjian)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton.toggled['bool'].connect(MainWindow.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "选择性别"))
        self.radioButton.setText(_translate("MainWindow", "男生"))
        self.radioButton_2.setText(_translate("MainWindow", "女生"))

        self.pushButton.setText(_translate("MainWindow", "合成"))
        self.label_3.setText(_translate("MainWindow", "本人软件归作者所有"))
        self.label_4.setText(_translate("MainWindow", ""))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.actionDakai.setText(_translate("MainWindow", "打开"))
        self.actionTuichu.setIconText(_translate("MainWindow", "退出"))
        self.actionQingkong.setText(_translate("MainWindow", "清空"))
        self.actionJianqie.setText(_translate("MainWindow", "剪切"))
        self.actionFuzhi.setText(_translate("MainWindow", "全选"))
        self.actionZhantie.setText(_translate("MainWindow", "粘贴"))
        self.action.setText(_translate("MainWindow", "用户"))
        self.actionZuozhe.setText(_translate("MainWindow", "作者"))
        self.actionRuanjian.setText(_translate("MainWindow", "关于"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

